// const ACTION={
//     USER_LOGGED_IN:"USER_LOGGED_IN",
//     CLOUDINARY_IMAGE:"CLOUDINARY_IMAGE",
//     SEARCH_POST:"SEARCH_POST",
//     CHALLENGE_POST:"CHALLENGE_POST",
//     COMMUNITY_POST:"COMMUNITY_POST",
//     COMMUNITY:"COMMUNITY"
// }

// export default ACTION


export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const CLOUDINARY_IMAGE = "CLOUDINARY_IMAGE";
export const SEARCH_POST = "SEARCH_POST";
export const CHALLENGE_POST = "CHALLENGE_POST";
export const COMMUNITY_POST = "COMMUNITY_POST";
export const COMMUNITY = "COMMUNITY";
export const TOGGLE_CHAT_CONTACT="TOGGLE_CHAT_CONTACT"
